name: amazy_app
description: amazy_app Mobile App

publish_to: 'none'

version: 1.2.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  get:
  google_fonts:
  font_awesome_flutter:
  share:
  http:
  image_picker:
  dio:
  persistent_bottom_nav_bar:
  google_sign_in:
  firebase_auth:
  firebase_core:
  expandable:
  octo_image:
  animated_splash_screen:
  shared_preferences:
  url_launcher:
  country_code_picker:
  pin_code_fields:
  dotted_border:
  flutter_svg:
  dotted_line:
  expansion_tile_card:
  flutter_rating_bar:
  flutter_slidable:
  slide_countdown_clock:
  flutter_animation_progress_bar:
  timelines:
  clipboard:
  extended_nested_scroll_view:
  flutter_page_indicator:
  transformer_page_view:
  flutter_spinkit:
  fancy_shimmer_image:
  get_storage:
  cached_network_image:
  intl:
  flutter_cupertino_datetime_picker: 
    git: https://github.com/emran92/flutter_cupertino_datetime_picker
  avatar_glow:
  file_picker:
  loading_skeleton:
  flutter_easyloading:
  scratcher:
  share_plus:
  animate_do:
  stripe_payment:
  razorpay_flutter:
  webview_flutter:
  http_auth:
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  flutter_webview_plugin:
  flutter_inappwebview:
  flutterwave_standard:
  multi_select_flutter:
  flutter_xlider:
    git:
      url: https://github.com/swaroopsuthar/flutter_xlider.git
      ref: master
  loading_more_list:
  supercharged:
  pay:
  flutter_staggered_grid_view:
  photo_view:
    git: https://github.com/bluefireteam/photo_view.git
  stripe_sdk:
  paytm_allinonesdk:
  easy_search:
  hive:
  hive_flutter:
  flutter_html:
  dio_http_cache:
  circular_countdown_timer:
  badges:
  flutter_facebook_auth:
  sign_in_with_apple:
  flutter_polygon_clipper:
  flutter_countdown_timer:
  async:
  group_radio_button:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.2
  flutter_launcher_icons: ^0.9.2
  hive_generator: ^1.1.1
  build_runner: ^2.1.7

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/config/app_logo.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FF3364"
  image: assets/config/splash_screen_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/images/
     - assets/config/
     - assets/fonts/
     - assets/payment/

  fonts:
    - family: CircularStdLight
      fonts:
        - asset: assets/fonts/CircularStd-Light.otf
    - family: CircularStdBlack
      fonts:
        - asset: assets/fonts/CircularStd-Black.otf
    - family: CircularStdBold
      fonts:
        - asset: assets/fonts/CircularStd-Bold.otf
    - family: CircularStdMedium
      fonts:
        - asset: assets/fonts/CircularStd-Medium.otf
    - family: CircularStdBook
      fonts:
        - asset: assets/fonts/CircularStd-Book.otf